name:                train
version:             0.1.0.0
github:              "cspollard@gmail.com/train"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com"
copyright:           "Chris Pollard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cspollard@gmail.com/train#readme>

default-extensions:
- DerivingVia
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- GADTs
- RankNTypes
- PatternSynonyms
- TypeOperators
- TypeApplications
- KindSignatures
- PolyKinds
- DataKinds
- ScopedTypeVariables
- ExistentialQuantification

dependencies:
- base >= 4.7 && < 5
- extensible
- bifunctors
- profunctors
- semigroupoids
- free-algebras

library:
  source-dirs: src
